INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (1, 1, 'social', 'www.facebook.com', '9873masdsa7','aliceFb');
INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (1, 1, 'work related', 'www.lighthouselabsadmin.com', '&h12hs^','aliceLHL');
INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (1, 1, 'social', 'www.reddit.com', 'dlksaj87s', 'aliceRed');
INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (1, 2, 'work related', 'www.amazonworklogin.com', '09asj2d', 'Aamazon');
INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (2, 3, 'entertainment', 'www.youtube.com', 'fkjashfjaks8','KiraWorld');
INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (2, 3, 'social', 'www.tiktok.com', '*2ksa292','tiktik');
INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (2, 3, 'work related', 'www.shopifydeveloperlogin.com', 'kjhasd72*^','KirShopi');
INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (3, 3, 'social', 'www.instagram.com', 'dkja8&j','EkInsta');
INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (3, 3, 'social', 'www.tweeter.com', 'dlsadasdfa','EkTweet');
INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (3, 3, 'work related', 'www.shopifyadminlogin.com', '9fasfs','EkShopify');
INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (4, 1, 'entertainment', 'www.disneyplus.com', 'kjhsa8h&','HelloDisney');
INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (4, 2, 'social', 'www.twitter.com', 'uiha78s68aj','HelloT');
INSERT INTO passwords (user_id, organization_id, category, url, password_text, username) VALUES (4, 2, 'entertainment', 'www.netflix.com', 'lhsafua','HelloNet');
