
INSERT INTO passwords (WEBSITE_NAME, WEBSITE_USERNAME, WEBSITE_PASSWORD, ORGANIZATION_ID, CATEGORY_ID)
VALUES ('zoom', 'Lighthouse-LHL', 'superpassword', 1, 2);

INSERT INTO passwords (WEBSITE_NAME, WEBSITE_USERNAME, WEBSITE_PASSWORD, ORGANIZATION_ID, CATEGORY_ID)
VALUES ('slack', 'Lighthouse-LHL', 'superpassword', 1, 2);

INSERT INTO passwords (WEBSITE_NAME, WEBSITE_USERNAME, WEBSITE_PASSWORD, ORGANIZATION_ID, CATEGORY_ID)
VALUES ('compass', 'Lighthouse-LHL', 'superpassword', 1, 2);

INSERT INTO passwords (WEBSITE_NAME, WEBSITE_USERNAME, WEBSITE_PASSWORD, ORGANIZATION_ID, CATEGORY_ID)
VALUES ('twitter', 'LighthouseLabs', 'superpassword', 1, 1);
